<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?= $alert ?>" role="alert"><?= $message ?></div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $data['name'] ?></h1>
        <div class="table-responsive">
            <table data-test="url" class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $data['id'] ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $data['name'] ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $data['created_at'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= $data['id'] ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover mt-3" data-test="checks">
            <tbody>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                <?php foreach ($checkData as $check) : ?>
                    <tr>
                        <td><?= $check['id'] ?? '' ?></td>
                        <td><?= $check['status_code'] ?? '' ?></td>
                        <td><?= $check['h1'] ?? '' ?></td>
                        <td><?= $check['title'] ?? '' ?></td>
                        <td><?= $check['description'] ?? '' ?></td>
                        <td><?= $check['created_at'] ?? '' ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>
