<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table data-test="urls" class="table table-bordered table-hover text-nowrap " data-test="urls">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>

                    <?php foreach ($data as $key => $url) : ?>
                        <tr>
                            <td><?= $url['id'] ?></td>
                            <td><a href="/urls/<?= $url['id'] ?>"><?= $url['name'] ?></a></td>
                            <td><?= $url['created_at'] ?? '' ?></td>
                            <td><?= $url['status_code'] ?? '' ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</main>
